### ISSUE TITLE
怎么快速的移植到自己程序里面

### ISSUE THREAD

**Issue by Warm-rain** [oddstab/CardReaderDemo#1]
你好，这个项目真的很棒，我想把它移植到自己的项目里面，怎么可以快速的完成，我的是一个c#窗口项目

**Comment by oddstab** [comment]
@Warm-rain 因為沒有發布到nuget上，所以clone下來後引用CardReaderLib就ok囉

**Comment by Warm-rain** [comment]
嗯，研究了一下还是很方便的，直接生成dll调用就可以了,谢谢老哥的回答，欢迎以后来重庆吃火锅，现在有直达列车了哟

**Comment by oddstab** [comment]
哈哈 還沒去過中國呢，有空一定去逛逛~
